# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Faucet < Formula
  desc "Turn any database into a secure REST API. One binary. One command."
  homepage "https://faucet.dev"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faucetdb/faucet/releases/download/v0.1.2/faucet_0.1.2_darwin_amd64.tar.gz"
      sha256 "75eca91166bca2a243933d169c99a2ee648dd991cd17a46bf1da4427f03f8834"

      def install
        bin.install "faucet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faucetdb/faucet/releases/download/v0.1.2/faucet_0.1.2_darwin_arm64.tar.gz"
      sha256 "c5ef919ec1b07da5d5544247b1b86f02f0d7cf9d0ae3e6c816bda2f8eca90552"

      def install
        bin.install "faucet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faucetdb/faucet/releases/download/v0.1.2/faucet_0.1.2_linux_amd64.tar.gz"
      sha256 "dec8a7dc99eae804be3ed6d81cc6a899eaa3fbabf3873c43b15cb94d9bd74068"
      def install
        bin.install "faucet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faucetdb/faucet/releases/download/v0.1.2/faucet_0.1.2_linux_arm64.tar.gz"
      sha256 "e5c9b14c4e9c5f010ae62ff073827f4a0c8126f3380b09a06a3c4f1a6c78d558"
      def install
        bin.install "faucet"
      end
    end
  end

  test do
    system "#{bin}/faucet", "version"
  end
end
